name : hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository code
        uses: actions@v3
      - run: echo "$(cat hello_word.txt)"  
    
      

